apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-tower
  labels:
    app: main-tower
  annotations:
    linkerd.io/inject: enabled
    enable-opentracing: "true"
    zipkin-collector-host: linkerd-collector.linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-tower
  template:
    metadata:
      labels:
        app: main-tower
    spec:
      containers:
      - name: main-tower
        image: apolzek/main-tower:0.2
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: main-tower
spec:
  selector:
    app: main-tower
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
